version: '3.9'

services:
  jenkins:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: jenkins
    restart: always
    privileged: true
    user: root

    healthcheck:
      test: curl -s https://localhost:8080 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 1m
      timeout: 5s
      retries: 3

    ports:
      - '8080:8080'
    networks:
      - default
    environment:
    - JAVA_OPTS:-Djava.awt.headless=true
    volumes:
      - C:/jenkins:/var/jenkins_home
      - C:/jenkins/run/docker.sock:/var/run/docker.sock

networks:
  default: