services:
 mongo:
   image: mongodb/mongodb-community-server
   hostname: mongo
   volumes:
   - C:\data\db:/data/db
   - C:\data\backup:/data/backup
   tty: true
   stdin_open: true
   container_name: mongo
 nlweb-backend:
   # NeoLoad Web Backend:
   # - 8080: NeoLoad GUI REST Port
   # - 8081: Public API Swagger Port
   # - 9092: NeoLoad Web BackendEnd Monitoring
   ports:
   - 8080:1081
   - 8081:1082
   - 9082:9092
   image: neotys/neoload-web-backend
   environment:
     START_MODE: ON_PREMISE
     MEMORY_MAX: 1300m
     MONGODB_HOST: mongo
     MONGODB_PORT: 27017
     MONGODB_MAX_POOLSIZE: 50
     JETTY_DYNAMIC_PORT: "false"
     JETTY_PORT: 9092
     SAAS: "false"
     PRODUCT_NAME: NeoLoad
     NLWEB_SECRET_KEY: MySecretKeyForNeoLoadWeb
   links:
   - mongo
   tty: true
   stdin_open: true
   container_name: nlweb-backend
 nlweb-frontend:
   # NeoLoad Web Frontend:
   # - 80: NeoLoad Web Interface
   # - 81: NeoLoad Web FrontEnd Monitoring
   ports:
   - 80:9090
   - 81:9091
   image: neotys/neoload-web-frontend
   environment:
     START_MODE: ON_PREMISE
     MEMORY_MAX: 896m
     JETTY_DYNAMIC_PORT: "false"
     JETTY_PORT: 9090
     ADMIN_PORT: 9091
     SAAS: "false"
     PRODUCT_NAME: NeoLoad
   links:
   - nlweb-backend
   tty: true
   stdin_open: true
   container_name: nlweb-frontend
 nlweb-loadgen:
  image: neotys/neoload-loadgenerator:latest
  environment:
    NEOLOADWEB_URL: 'https://neoload-api.saas.neotys.com/'
    NEOLOADWEB_TOKEN: '2614b1e58589687c4b3122f84b2667db0b1edc8a2eb0a9f7'
  ports:
    - '7101:7100'
  expose:
    - '7101'
  links:
   - nlweb-backend
  container_name: nlweb-loadgenerator
 nlweb-controller:
  image: neotys/neoload-controller:latest
  environment:
    MODE: 'Managed'
    NEOLOADWEB_URL: 'https://neoload-api.saas.neotys.com/'
    NEOLOADWEB_TOKEN: '2614b1e58589687c4b3122f84b2667db0b1edc8a2eb0a9f7'
    NTS_URL: https://neoload.saas.neotys.com/
    NTS_LOGIN: 'admin:nlweb-password-changeit'
  links:
   - nlweb-backend
  container_name: nlweb-controller

 