version: '3'

services:
    db:
      image: "mysql:latest"
      environment:
        MYSQL_DATABASE: 'school'
        MYSQL_PASSWORD: 'root'
        MYSQL_ROOT_PASSWORD: 'root'
      ports:
          - "3306:3306"
      expose:
        - '3306'
      volumes:
          - ./my-db:/var/lib/mysql
    schoolweb:
      depends_on: 
          - db
      build:
          context: ./
          dockerfile: ./Dockerfile
      image: "schoolweb:latest"
      ports:
          - "3001:3001"